version: 0.2
phases:
  install:
    runtimeVesrion: openjdk-17-jdk
  pre_build:
    commands:
      - apt-get update -y
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzvf apache-maven-3.9.6-bin.tar.gz
      - ln -s apache-maven-3.9.4 maven
  build:
    commands:
      - mvn compile
      - mvn test
      - mvn package
artifacts:
  files:
     - target/**/*.jar
