version: 0.2
env:
  secrets-manager:
    ACCESS_KEY: Buils-Sec:AccessKey
    SECRET_KEY: Buils-Sec:SecretKey
    LOGIN: Buils-Sec:Sonar-Token
    HOST: Buils-Sec:HOST
    Organization: Buils-Sec:Organization
    Project: Buils-Sec:Project
    AWS_ACCOUNT_ID: Buils-Sec:AccID
phases:
  install:
    runtimeVersion: openjdk-17-jdk
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y jq
      - apt-get install unzip -y
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzvf apache-maven-3.9.6-bin.tar.gz
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:./sonar-scanner-cli-5.0.1.3006-linux/bin/
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - mvn compile
      - mvn test
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.organization=$Organization -Dsonar.projectKey=$Project
      - mvn package
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG  $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - aws eks update-kubeconfig --region ap-south-1 --name EKS-Ops-Cluster
      - kubectl apply -f deployment-svc.yml
artifacts:
  files:
     - target/**/*.jar
  name: "artifact-${CODEBUILD_BUILD_NUMBER}.jar"
