apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: jvm-app
  replicas: 3
  template:
    metadata:
      labels:
        app: jvm-app
    spec:
      containers:
      - name: app-cn
        image: $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: jvm-svc
spec:
  selector:
    app: jvm-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
